{
 "title": "GrowattDashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select sum(kilowatthour) from kwh",
     "rawQueryText": "select sum(kilowatthour) from kwh",
     "timeColumns": [ "timestamp" ]
    }
   ]
  },
  {
   "title": "Day Average",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select max(kilowatthour) from kwh",
     "rawQueryText": "select max(kilowatthour) from kwh",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Daily Average",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT avg(kilowatthour) from kwh",
     "rawQueryText": "SELECT avg(kilowatthour) from kwh",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "30 Day Average",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT avg(monthlykwh) from (\n  SELECT\n  $__unixEpochGroupSeconds(\"timestamp\", 2592000) as time,\n  sum(kilowatthour) as monthlykwh\n  FROM kwh\n  GROUP BY time\n  ORDER BY time\n)",
     "rawQueryText": "SELECT avg(monthlykwh) from (\n  SELECT\n  $__unixEpochGroupSeconds(\"timestamp\", 2592000) as time,\n  sum(kilowatthour) as monthlykwh\n  FROM kwh\n  GROUP BY time\n  ORDER BY time\n)",
     "timeColumns": [
      "time",
      "ts",
      "timestamp"
     ]
    }
   ]
  },
  {
   "title": "Daily Power (KWh)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "queryText": "SELECT\n  timestamp,\n  sum(kilowatthour) as Daily\n  FROM kwh\n  GROUP BY timestamp\n  ORDER BY timestamp\n",
     "rawQueryText": "SELECT\n  timestamp,\n  sum(kilowatthour) as Daily\n  FROM kwh\n  GROUP BY timestamp\n  ORDER BY timestamp\n",
     "timeColumns": [
      "time",
      "timestamp"
     ]
    }
   ]
  },
  {
   "title": "Power (AC)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "queryText": "SELECT\n  $__unixEpochGroupSeconds(\"timestamp\", 3600) as time,\n  sum(watt) as DailyWatts\n  FROM pac\n  GROUP BY time\n  ORDER BY time",
     "rawQueryText": "SELECT\n  $__unixEpochGroupSeconds(\"timestamp\", 3600) as time,\n  sum(watt) as DailyWatts\n  FROM pac\n  GROUP BY time\n  ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}